# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfcc2c3529505ab073b83ce3ded1ccbe26e9149bf414bd0619ad8c8cfbf13246142c9f960e8855234e3d2c223bde9cd2120eaafa60cbf1c5d877a1ccec59a710

test:
  secret_key_base: b8fac0318365ed29a8203e76a059735863c5f7f0085113df53bcd8884a0326f2630b8bdd531c10f79417c13affbe22b84af61028be9cdb3f3ced74221bc5fa3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
